compressionLevel: mixed

enableGlobalCache: true

nmHoistingLimits: none

nmMode: classic

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-NONE}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
